# SFDX configuration + source validation targeting user
name: SFDC CI CD with Salesforce CLI
on: [push]
jobs:
  sfdx_ci_cd:
    runs-on: ubuntu-latest
    name: SFDX usage with Git
    steps:
      # use GitHub Action to configure SFDX.
      - name: Salesforce CLI Setup
        uses: karamchandanid/sfdx-setup@v1
        id: sfdx_setup
        with:
          sfdc_client_id: ${{ secrets.SFDC_CLIENT_ID }}
          sfdc_client_secret: ${{ secrets.SFDC_CLIENT_SECRET }}
          user_name: ${{ secrets.SFDC_DEV_USERNAME }}
          password: ${{ secrets.SFDC_DEV_PASSWORD }}
          login_url: https://login.salesforce.com
      
      # Checkout the source code, need this to get repo, to pass "This directory does not contain a valid Salesforce DX project."
      - name: 'Checkout source code'
        uses: actions/checkout@v2
      
      # valdating source to org
      - name: 'Validating Source to org'
        run: |
          if [[ ${{ steps.sfdx_setup.outputs.sfdx_configured }} == 'true' ]]
          then
            # following usage fir Demo only, "SFDX version" | "Displaying Org details" | "Displaying User details"
            echo "SFDX version"
            echo "-------------------------"
            sfdx -v
            echo "Displaying Org details..."
            echo "-------------------------"
            sfdx force:org:display
            
            echo "Displaying User details..."
            echo "-------------------------"
            sfdx force:user:display

            # echo "Validating source to target org..."
            # echo "-------------------------"
            # no need to specify --targetusername
            sfdx force:source:deploy -p force-app/main/default -c
            
          else
            echo ${{ steps.sfdx_setup.outputs.error }}
            echo ${{ steps.sfdx_setup.outputs.error_description }}
          fi
